<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{d6de15a2-09c7-4c79-a810-9b276e90cec0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	cnt : DINT;
	nPositionH : REAL;
	nPositionV : REAL;
	bExecuteGantryMove : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[cnt := cnt + 1;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>